### PR TITLE
the ability to set all property values instead of only the plugins

### PR DESCRIPTION
**Pull request by ramonskie**
we want to be able to set all property values
according to https://confluence.atlassian.com/display/STASH/Stash+config+properties

### CODE REVIEW

**Comment by bflad** [comment]
Can you please make this change backwards compatible? We can consider deprecating the plugin attribute in a future major release. Thanks!

**Comment by ramonskie** [comment]
yup will do in this weekend

**Comment by bflad** [comment]
Great work! I'll get this merged, documented, and released in 3.14.0 tomorrow. Thanks so much.

**Comment by legal90** [comment]
@ramonskie :+1: Thanks a lot!

**Pull request merged**
