### PR TITLE
Update mysql cookbook (6.x) and database cookbook

### PR DESCRIPTION
**Pull request by patcon**
I think we could do this pretty easily. Looking at the other issue, it seems the only problem was that when the database cookbook bumped major versions, it abstracted out a recipe (mysql2_chef_gem), and I think we could just add that back in

### CODE REVIEW

**Comment by linc01n** [comment]
Hmm... 
When I test run it, it gives me error

```
==> centos6: NoMethodError
==> centos6: -------------
==> centos6: undefined method `version' for Chef::Resource::MysqlClient
==> centos6:
==> centos6:
==> centos6: Cookbook Trace:
==> centos6: ---------------
==> centos6: /tmp/vagrant-chef/6d85d9c914cef1b3ceae556d9c1d3737/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
==> centos6: /tmp/vagrant-chef/6d85d9c914cef1b3ceae556d9c1d3737/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
```

**Comment by patcon** [comment]
Seems you're still using v5.x mysql cookbook series? Maybe check your berksfile.lock to confirm?

**Comment by linc01n** [comment]
I am afraid I was locked to 5.x

https://github.com/bflad/chef-stash/pull/103/files#diff-9fd042d4cd1e8f82894bbd7dffb313ecR30

**Comment by mrjcleaver** [comment]
There seems to be a bunch of code in various branches on the network https://github.com/bflad/chef-stash/network, including @andrewgoktepe 's at  https://github.com/andrewgoktepe/chef-stash/commit/465275220f9876fb57154bf96115a31773d1bdb2

**Comment by patcon** [comment]
FYI, I think I got this working, but let's get postgresql test suite (#107) running before merging this, and I can rebase

(I'm using it from my feature branch for mysql, but not postgresql yet, and can't say with 100% certainty that it works for both)

**Comment by patcon** [comment]
Just rebased on master and updated issue title to better reflect work

**Comment by linc01n** [comment]
:+1: Merged but I changed `README.md` and `metadata.rb`

**Pull request merged**
