### PR TITLE
Add postgresql test suite

### PR DESCRIPTION
**Pull request by patcon**
I've got this in another branch too, and I can push it after we merge https://github.com/bflad/chef-stash/pull/105

Woo

- [x] centos-6
- [x] centos-7
- [x] ubuntu-12.04
- [x] ubuntu-14.04

### CODE REVIEW

**Comment by patcon** [comment]
Note that this PR will be much much smaller once #105 gets merged :)

**Comment by patcon** [comment]
OK, everything passes! Ready to rock whenever you're comfortable doing so

**Comment by linc01n** [comment]
Give me few hours for me to go back home and have a look.

**Comment by patcon** [comment]
No hurry! It's my very late bedtime now anyhow..!

**Comment by linc01n** [comment]
:+1: Merged

**Pull request merged**
