### PR TITLE
Moved checksum's and download url calculation into helper.rb 

### PR DESCRIPTION
**Pull request by katbyte**
This allows calling cookbooks to change the version on the fly. 

Followed the pattern in:
- https://github.com/parallels-cookbooks/confluence
- https://github.com/bflad/chef-jira
- https://github.com/afklm/crowd

Issue #167

### CODE REVIEW

**Comment by katbyte** [comment]
Disabled some rubucop metrics to get the build to pass...

**Comment by katbyte** [comment]
@linc01n I noticed you merged the versions PR. Rebased this off that branch so there would be no merge conflict. If you accept this one i also have the newest version checksums added and can create a PR for them aswell: 

https://github.com/katbyte/chef-stash/tree/versions.201610

**Comment by iluxame** [comment]
@katbyte we also waiting for this PR. Do you intend to fix coding style stuff in order to pass CI?

**Comment by katbyte** [comment]
@iluxame I have rebased this PR off the latest master, however the errors causing the CI build to fail do not seem related to my changes (however i could be wrong) 
screen shot 2017-05-30 at 16 13 17

@linc01n Is there a reason this PR was not merged? Is there anything I can improve/fix?

**Comment by linc01n** [comment]
Sorry for the late reply.
What I am concerned is moving this out of the `attribute.rb` is that the right way to do.
I asked this question to some chef people when I was attending a workshop. He said it should be fine. 

Going to merge this PR now.

Thanks!

**Comment by linc01n** [comment]
Fixed the rubocop and foodcritic error. Changed the helper a bit in #182

**Pull request merged**
