### PR TITLE
Switch to using MySQL 5.5 by default

### LINKED ISSUE #111: Cannot install mysql-client 5.6 on Ubuntu 12.04
For ubuntu 12.04 LTS, the `kitchen test` failed because it cannot install mysql client 5.6.

http://packages.ubuntu.com/search?keywords=mysql-client

/cc @patcon

### PR DESCRIPTION
**Pull request by patcon**
Resolves #111

Was using 5.6, but not available on Ubuntu 12.04.

### CODE REVIEW

**Comment by patcon** [comment]
Tested:

- [x] mysql-centos-6
- [x] mysql-centos-7
- [x] mysql-ubuntu-1204
- [x] mysql-ubuntu-1404

**Comment by linc01n** [comment]
:+1: Merged :exclamation:

**Comment by bflad** [comment]
FWIW -- I'd suggest deprecating 12.04 support going forward (next major release?). 14.04 LTS is over 15 months old now and Ubuntu folks seem quite on top of upgrading.

**Comment by linc01n** [comment]
I checked the LTS support time. It is 5 years. I think we can drop it once we default to postgres.
https://wiki.ubuntu.com/LTS

**Comment by bflad** [comment]
Ah good call on the official documentation. Really I'd leave it up to all the maintainers to decide the amount of "burden" supporting the older OSes is on us. If changes remain easy, I'd stick with listing it as supported. Personally, I think this was a good fix which you might want to add some README notes about why the attribute exists. :+1:

**Pull request merged**
