### PR TITLE
Use proper setenv.sh format for v3.8+.

### LINKED ISSUE #84: Stash Crashes Due to java.lang.OutOfMemoryError PermGen Space Error
I have this issue twice after I upgraded my Stash to 3.8.0 4 days ago. The solution is to increase

```ruby
default['stash']['jvm']['maximum_permgen'] = '256m'
```

I am still testing how many ram should I increase

From Stash Knowledge base:
> If you're experiencing this issue after upgrading to Stash 3.8+ and are using Java 7, it's likely that the setenv.sh (setenv.bat for Windows) was copied from a previous version. 

screen shot 2015-04-24 at 11 43 32 am

source: https://confluence.atlassian.com/display/STASHKB/Stash+Crashes+Due+to+java.lang.OutOfMemoryError+PermGen+Space+Error

### PR DESCRIPTION
**Pull request by patcon**
Fixes #84

### CODE REVIEW

**Comment by patcon** [comment]
I was hoping to add serverspec tests for this before merging. Any concerns with that @linc01n?

**Comment by linc01n** [comment]
Thanks for the pull request @patcon 

Adding serverspec is welcome. I am thinking creating a new template for this and use different template for different stash version.

I am working on this file also. It looks like this at the moment. 
https://gist.github.com/linc01n/29cf02c3c8d295776289

It seems there are more changes than the permgen line. `JMX_REMOTE_PORT` is missing in the template and the way Atlassian setting for `STASH_HOME` path changed a bit.

**Comment by patcon** [comment]
No prob!

Ok, since it seems the cross-compat per minor version, might be more maintainable and clear to choose the template source based on `node['stash']['version']` :) Any objection to merging this for now, or at least until you get it done your way?

**Comment by linc01n** [comment]
Let me merge your commit and refractor it later. So people can at least lock to git version of the cookbook and no need to wait my release.

**Comment by patcon** [comment]
:+1: I'll likely work on AWS + travis integration on friday. My client, Blended Perspectives, is happy to front the AWS fees, if you're comfortable giving me push access once I get it going. That way, I can upload an AWS key as an encrypted envvar.

**Comment by linc01n** [comment]
Thanks @patcon . Would love that. Now I run `kitchen test` on my machine every time before I release it. It just takes too long.

**Pull request merged**
