### PR TITLE
Bitbucket 5 support

### PR DESCRIPTION
**Pull request by jtusz**
Experimental support for Bitbucket 5 (Issue #181).

Added:
Hashes for Bitbucket 5.0.0, 5.1.x
Systemd compatibility
Templates and configs for Bitbucket 5.x.x
Minor changes (Ohai version, ignore .idea project files, etc.)
Ubuntu 16.04

Removed:
Ubuntu 12.04 (EOL)

There are some problems with CentOS, but they are also present in the projects master branch. Ubuntu 14.04 and 16.04 are working without any visible problems.

Update: 
Builds on Travis CI are failing, will debug it in the next days.

### CODE REVIEW

**Comment by jtusz** [comment]
Chefspec tests in default_spec.rb are updated and everything passes.

**Comment by linc01n** [comment]
Thanks! I tried to run on my centos 6 4.14.5. It can't completed due to my server doesn't have systemd.

**Comment by jtusz** [comment]
Thanks for feedback. The lack of systemd should't be a problem, the cookbook should check if initV or systemd is present and which should be used. I will look into it and improve the code.

**Comment by jtusz** [comment]
D'oh. I almost forgot about this. CentOS 6 is now supported with InitV.

**Pull request merged**
